### PR TITLE
Mounting with an IP Address through AWS CloudFormation

### PR DESCRIPTION
**Pull request by karan6190**
Updated the User Guide with Mounting Efs With an IP Address through AWS CloudFormation.

As I have included Config file in the Updated Document, so just let me know whether conf file should be included in some other repository and link is provided for making the doc short and simple

### CODE REVIEW

**Comment by awsdan** [comment]
Hi there! Thanks for the pull request. AWS CloudFormation sample templates live here: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/quickref-efs.md

Feel free to make a pull request on that doc set, and I'll be sure to link to them from this page.

Thanks again for the PR!

-Dan

**Comment by karan6190** [comment]
Hey Dan, thanks for your suggestion. I just want to know that should I make separate Template as suggested doc set is specific through filesystemID

**Comment by awsdan** [comment]
There can be multiple templates and template snippets on the same page. See https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/quickref-s3.md as an example

**Comment by karan6190** [comment]
Hey Dan, thanks for your Help. I have submitted PR on that Doc set

**Comment by awsdan** [comment]
My pleasure! Please share a link to the other PR when you create it so I can track it and add a link to it accordingly.

**Comment by karan6190** [comment]
Hey, here is the link - https://github.com/awsdocs/aws-cloudformation-user-guide/pull/105

please let me know any changes required on sample template side, as I have just added the sample template for Mounting

**Comment by awsdan** [comment]
Thanks! More to come soon :)

**Comment by karan6190** [comment]
Hey dan, that PR is not reviewed and merged but the same script is merged on beanstalk-example repo (https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/community-provided/instance-configuration/storage-efs-mountfilesystem-ip-addr.config).

So can you please link the page

**Comment by awsdan** [comment]
I've added the link to the docs, and I will close this pull request. Thanks for your contribution!

**Pull request closed without merging**
